project:
  type: website
  output-dir: docs
  # add files to render specific files and orders
  # files:
  #   - "**.qmd"
  #   - "media/**"
  #   - "data/**"  
  preview:
   # watch for changes in input files
    watch-inputs: true
    # open brower once complete
    browser: true

website:
  title: "Samantha P"
  google-analytics: "G-SC9L5BGV9Z"
  navbar:
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: analysis.qmd
      - href: about.qmd
        text: About

    right:
      - icon: envelope-fill
        href: mailto:theflow365@emailhub.kr
      - icon: linkedin
        href: https://www.linkedin.com/in/samantha-p5221/
        target: _blank
      - icon: github
        href: https://github.com/Pylon521/
        target: _blank
      - icon: share-fill
        href: "https://www.linkedin.com/sharing/share-offsite/?url=https://pylon521.github.io/samanthaPortfolio/"
        target: _blank


  # sidebar: 
  #   style: "floating"
  #   background: light      # light | dark | auto
  #   contents: 
  #     - href: index.qmd
  #       text: Home
  #     - section: "Projects"
  #       contents: 
  #       - href: marketTrendAnalysis.qmd
  #         text: Market Trend Analysis
  #       - href: webScraper.qmd
  #         text: US Treasury Bond Web Scraper
  #       - href: invertedYieldCurve.qmd
  #         text: Inverted Yield Curve Analysis
  #       - href: PCA.qmd
  #         text: Treasury Yields PCA
  #     - href: about.qmd
  #       text: About

  page-footer:
    center:
      - text: "© 2025 Samantha P"

format:
  html:
    theme: flatly
    css: styles.css
    output-dir: docs
    # share: # does not work with flatly
    #   linkedin: true
    # toc: false
    # code-fold: true

execute:
# true to disable reruning
  cache: true
  # show codes in output docs
  echo: true
  # suppress script warnings in output docs
  warning: false
